name: Lint

on:
  push:
    branches: [master]
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run:
          pip install pillow==9.5.0 -r ./requirements_dev.txt

      - name: Lint
        run: make lint
